baseurl: "https://fishycat.netlify.com/"
languageCode: "en-us"
title: "fishycat"
theme: "hugo-ivy"
googleAnalytics: "UA-104890341-1"
disqusShortname: "https-fishycat-netlify-com"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 3
    - name: "关于"
      url: "/cn/about/"
      weight: 4
    - name: "博客"
      url: "/cn/"
      weight: 5
    - name: "Tags 标签"
      label: "tags"
      url: "/tags/"
      weight: 6
    - name: "Categories 分类"
      label: "categories"
      url: "/categories/"
      weight: 7

      
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "Tags 标签"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "Categories 分类"
      label: "categories"
      url: "/categories/"
      weight: 6
    - name: "中文"
      url: "/cn/"
      weight: 7
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "Tags 标签"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "Categories 分类"
      label: "categories"
      url: "/categories/"
      weight: 6
    - name: "English"
      url: "/en/"
      weight: 7

params:
  description: "A little bit of data, and me"
  footer: "&copy; [Hong Zheng](/) 2017 - 2018 | [Github](https://github.com/zhengh42) "
  disqusURL: "https://fishycat.netlify.com"
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]
  githubContentURL: "https://github.com/zhengh42/hong_pages/tree/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.jpg"
      url: "/"
      alt: "Hong Zheng"
      tag: ""

  author:
    en: "Hong Zheng"
    cn: "苏木七"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]

taxonomies:
   tag : "tags"
   category : "categories"
